const ADD_CURRENCY = "ADD_CURRENCY",
      ADD_CONVERTER = "ADD_CONVERTER",
      REMOVE_CURRENCY = "REMOVE_CURRENCY",
      REMOVE_CONVERTER = "REMOVE_CONVERTER",
      FETCH_DATA = "FETCH_DATA",
      FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS",
      FETCH_DATA_ERROR = "FETCH_DATA_ERROR",
      UPDATE_SUCCESS = "UPDATE_SUCCESS",
      UPDATE_ERROR = "UPDATE_ERROR",
      SET_DATA_FROM_CACHE = "SET_DATA_FROM_CACHE";


export {
    ADD_CURRENCY,
    ADD_CONVERTER,
    REMOVE_CURRENCY,
    REMOVE_CONVERTER,
    FETCH_DATA,
    FETCH_DATA_SUCCESS,
    FETCH_DATA_ERROR,
    UPDATE_SUCCESS,
    UPDATE_ERROR,
    SET_DATA_FROM_CACHE
};